### ISSUE TITLE
Issue on button color

### ISSUE THREAD

**Issue by BibekBharati292511** [BibekBharati292511/WBMS#1]
Dear Ayush,
There had been some problems with the css of button color. As our system is water billing system, blue theme button is more preferable as it match our system. In the home page for user panel in banner section, green button with green background is used which is not visible properly . Besides that, spacing is also not proper, So, it needs to be changed.
In the payment section, blue color payment button would make more sense for our system, that needs to be addressed as soon as possible.
For the correction, you can use blue color theme for all buttons and maintain proper spacing among text paragraph and button in the banner section. 
![image](https://github.com/BibekBharati292511/WBMS/assets/107177344/ddd32e8b-d21a-441b-b8df-4907e881dd6d)

**Comment by Ayushzz12** [comment]
Sure, I have made the necessary changes to the CSS and ensured that the button color and spacing issues are resolved. 
<img width="931" alt="image" src="https://github.com/BibekBharati292511/WBMS/assets/107177211/359d234f-bd66-4863-8cbf-7bef58e2ccca">
