### ISSUE TITLE
User login page information section not visible properly

### ISSUE THREAD

**Issue by BibekBharati292511** [BibekBharati292511/WBMS#2]
In the login page, the information about the login criteria  is not visible enough as more attention is going to background rather than in information. 
In order to correct this, you can place a white theme banner behind the text of change text- color to make it more visible.
![image](https://github.com/BibekBharati292511/WBMS/assets/107177344/9af10563-3bb3-416e-9024-042e2f5d04d9)

**Comment by Ayushzz12** [comment]
I have made the changes, and the login criteria has now been visible than before. I also edited the CSS
<img width="483" alt="image" src="https://github.com/BibekBharati292511/WBMS/assets/107177211/9cd022eb-fafe-4ae7-bbb2-5765bdd61231">
